config/routes.rb
Rails.application.routes.draw do
   devise_for :users

  devise_scope :user do
    authenticated :user do 
      root "posts#index", as: :authenticated_root
    end

    unauthenticated :user do 
      root "devise/sessions#new"
    end
  end

  resources :posts do
    resources :comments
  end

  get "friends" => "friends#user_list"
  get ":id/send_friend_request" => "friends#send_friend_request",as: :send_friend_request
  get ":id/manage_friend_request" => "friends#manage_friend_request",as: :manage_friend_request
  get ":id/unfriend" => "friends#unfriend",as: :unfriend
  get ":id/friend_of_friend" => "friends#friend_of_friend",as: :friend_of_friend
  get ":id/cancel_sended_frnd_req" => "friends#cancel_sended_frnd_req",as: :cancel_sended_frnd_req

end

app/models/comment.rb
class Comment
	include Neo4j::ActiveNode
  property :title
  property :text
  property :created_at, :type => DateTime
  property :updated_at, :type => DateTime
  
  index :title
  
  has_one :out, :user, type: :commented_by
  has_one :out, :post, type: :comments_on
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_post, only: [:new, :create, :destroy, :update]
  # before_filter :authenticate_user

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        # create a relationship with a created property between post and comment
        # @post.comments.create(@comment, :created => Time.now.to_i)
        # alternative
        current_user.comments << @comment
        @post.comments << @comment

        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # it will automatically destroy the relationship as well
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @post }
      format.json { head :no_content }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params[:comment]
  end
end

app/views/comments/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for([@post, @comment]) do |f| %>
      <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
          <% @comment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

        <div class="field form-group">
          <%= f.label :title %><br />
          <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="field form-group">
          <%= f.label :text %><br />
          <%= f.text_area :text, class: 'form-control' %>
        </div>

        <div class="actions form-group">
        <%= f.submit nil, class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="text-center">New Comment</h1>
  </div>

  <%= render 'form' %>
</div>

<%= link_to 'Back', post_path(@post), class: 'btn btn-default' %>