config/routes.rb
Rails.application.routes.draw do
   devise_for :users

  devise_scope :user do
    authenticated :user do 
      root "posts#index", as: :authenticated_root
    end

    unauthenticated :user do 
      root "devise/sessions#new"
    end
  end

  resources :posts do
    resources :comments
  end

  get "friends" => "friends#user_list"
  get ":id/send_friend_request" => "friends#send_friend_request",as: :send_friend_request
  get ":id/manage_friend_request" => "friends#manage_friend_request",as: :manage_friend_request
  get ":id/unfriend" => "friends#unfriend",as: :unfriend
  get ":id/friend_of_friend" => "friends#friend_of_friend",as: :friend_of_friend
  get ":id/cancel_sended_frnd_req" => "friends#cancel_sended_frnd_req",as: :cancel_sended_frnd_req

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	before_action :get_user_detail,:only=>[:send_friend_request,:unfriend,:friend_of_friend,:manage_friend_request,:cancel_sended_frnd_req]
	def send_friend_request
		current_user.friendship.create(@requesting_user,:from_id=>current_user.uuid,:to_id=>@requesting_user.uuid, :created => Time.now.to_i)
		redirect_to friends_path
		flash[:notice] = "Friend request was sent successfully."
	end

	def manage_friend_request
		if params[:is_accept].to_s == "0"
			# reject
			@requesting_user.friendship.delete(current_user)
			flash[:notice] = "Friend request was rejcted."
		elsif params[:is_accept].to_s == "1"
			# accept
			current_user.friendship.create(@requesting_user,:from_id=>current_user.uuid,:to_id=>@requesting_user.uuid, :created => Time.now.to_i)
			flash[:notice] = "Friend request was accepted."
		end
		redirect_to friends_path
	end

	def cancel_sended_frnd_req
		current_user.friendship.delete(@requesting_user)
		flash[:notice] = "Sended Friend request was cancel successfully."
		redirect_to friends_path
	end

	def unfriend
		current_user.friendship.delete(@requesting_user)
		@requesting_user.friendship.delete(current_user)
		redirect_to friends_path
		flash[:notice] = "Unfriend successfully."
	end

	# return friends list and un friend users also
	def user_list
		users_uuids = User.all.map(&:uuid) - current_user.uuid.split(" ")
		@users = User.where(:uuid=>users_uuids)
	end

	def friend_of_friend
		@users = @requesting_user.friendship
		@friend_of_friend = @requesting_user.friendship.friendship
		@friend_of_friend_of_friend = @requesting_user.friendship.friendship.friendship

	end

	private
	def get_user_detail
		@requesting_user = User.find_by(:uuid=>params[:id])
	end
end

app/views/friends/friend_of_friend.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="text-center">Friend of Friends</h3>
  </div>

  <table class="table">
  	<tr>
  		<th colspan="" rowspan="" headers="" scope="">Name </th>
  		<th colspan="" rowspan="" headers="" scope="">Email </th>
  	</tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><% if current_user.is_friend?(user) %>
        			<%= link_to 'Unfriend', unfriend_path(user.uuid) , class: 'btn btn-info' %>
        			<%= link_to "Friend of Friend", friend_of_friend_path(user.uuid) %>
        		<% else %>
        			<%= link_to 'Send Friend Request',send_friend_request_path(user.uuid), class: 'btn btn-primary' %>
        		<% end %> 
        </td>
        
      </tr>
    <% end %>
  </table>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="text-center">Friend of Friends of Friends</h3>
  </div>

  <table class="table">
  	<tr>
  		<th colspan="" rowspan="" headers="" scope="">Name </th>
  		<th colspan="" rowspan="" headers="" scope="">Email </th>
  	</tr>
    <% @friend_of_friend.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><% if current_user.is_friend?(user) %>
        			<%= link_to 'Unfriend', unfriend_path(user.uuid) , class: 'btn btn-info' %>
        			<%= link_to "Friend of Friend", friend_of_friend_path(user.uuid) %>
        		<% else %>
        			<%= link_to 'Send Friend Request',send_friend_request_path(user.uuid), class: 'btn btn-primary' %>
        		<% end %> 
        </td>
        
      </tr>
    <% end %>
  </table>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="text-center">Friend of Friends of Friends of Friends</h3>
  </div>

  <table class="table">
  	<tr>
  		<th colspan="" rowspan="" headers="" scope="">Name </th>
  		<th colspan="" rowspan="" headers="" scope="">Email </th>
  	</tr>
    <% @friend_of_friend_of_friend.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><% if current_user.is_friend?(user) %>
        			<%= link_to 'Unfriend', unfriend_path(user.uuid) , class: 'btn btn-info' %>
        			<%= link_to "Friend of Friend", friend_of_friend_path(user.uuid) %>
        		<% else %>
        			<%= link_to 'Send Friend Request',send_friend_request_path(user.uuid), class: 'btn btn-primary' %>
        		<% end %> 
        </td>
        
      </tr>
    <% end %>
  </table>
</div>

app/views/friends/user_list.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="text-center">Listing Users</h1>
  </div>
      
 
  <table class="table">
  	<tr>
  		<th colspan="" rowspan="" headers="" scope="">Name </th>
  		<th colspan="" rowspan="" headers="" scope="">Email </th>
  	</tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
        <% if current_user.is_friend_requested?(user) && current_user.get_friend_requested?(user) %>
          <!-- friends -->
          <%= link_to 'Unfriend', unfriend_path(user.uuid) , class: 'btn btn-info' %>
          <%= link_to "Suggested Friends", friend_of_friend_path(user.uuid) %>
        <% elsif current_user.is_friend_requested?(user) %>
          <!-- only friend request sent -->
          <%= link_to 'Friend Request Already Sent',"#", class: 'btn btn-primary' %>
          <%= link_to 'Cancel Sended Friend Request',cancel_sended_frnd_req_path(user.uuid)+"?is_accept=0", class: 'btn btn-danger' %>
        <% elsif current_user.get_friend_requested?(user)%>
          <!-- only friend request accept -->
          <%= link_to 'Accept',manage_friend_request_path(user.uuid)+"?is_accept=1", class: 'btn btn-info' %>
          <%= link_to 'Reject',manage_friend_request_path(user.uuid)+"?is_accept=0", class: 'btn btn-danger' %>
        <% else %>
          <!-- no relationship -->
          <%= link_to 'Send Friend Request',send_friend_request_path(user.uuid), class: 'btn btn-primary' %>
        <% end %>
        	
        </td>
      </tr>
    <% end %>
  </table>
</div>