config/routes.rb
Rails.application.routes.draw do
   devise_for :users

  devise_scope :user do
    authenticated :user do 
      root "posts#index", as: :authenticated_root
    end

    unauthenticated :user do 
      root "devise/sessions#new"
    end
  end

  resources :posts do
    resources :comments
  end

  get "friends" => "friends#user_list"
  get ":id/send_friend_request" => "friends#send_friend_request",as: :send_friend_request
  get ":id/manage_friend_request" => "friends#manage_friend_request",as: :manage_friend_request
  get ":id/unfriend" => "friends#unfriend",as: :unfriend
  get ":id/friend_of_friend" => "friends#friend_of_friend",as: :friend_of_friend
  get ":id/cancel_sended_frnd_req" => "friends#cancel_sended_frnd_req",as: :cancel_sended_frnd_req

end

app/models/post.rb
class Post 
	include Neo4j::ActiveNode
  property :title
  property :text, default: 'bla bla bla'
  property :score, type: Integer, default: 0
  property :created_at, :type => DateTime
  property :updated_at, :type => DateTime
  
  validates :title, presence: true
  validates :score, numericality: { only_integer: true }

  index :title

  before_save do
    self.score = score * 100
  end
  
  has_many :in, :comments, origin: :post
  has_one :out, :user, type: :posted_by
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
  # before_filter :authenticate_user

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        current_user.posts << @post
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params[:post]
  end
end

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for(@post) do |f| %>
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field form-group col-md-10">
        <%= f.label :title %><br />
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="field form-group col-md-2">
        <%= f.label :score %><br />
        <%= f.number_field :score, class: 'form-control' %>
      </div>

      <div class="field form-group col-md-12">
        <%= f.label :text %><br />
        <%= f.text_area :text, class: 'form-control' %>
      </div>

      <div class="actions form-group col-md-12">
        <%= f.submit nil, class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="text-center">Editing post</h1>
  </div>

  <%= render 'form' %>
</div>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="text-center">Listing posts</h1>
  </div>

  <table class="table">
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= link_to 'Show', post, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-info' %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to 'New Post', new_post_path, class: 'btn btn-default' %>

app/views/posts/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="text-center">New post</h1>
  </div>

  <%= render 'form' %>
</div> 

<%= link_to 'Back', posts_path, class: 'btn btn-default' %>

app/views/posts/show.html.erb
<% if notice %>
  <div id="notice" class="well bg-info">
    <%= notice %>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h1>
      <%= @post.title %>
      <br>
      <small>Score: <%= @post.score %></small>
    </h1>
  </div>

  <div class="panel-body lead">
    <%= @post.text %>
  </div>

  <div class="panel-footer">
    <h3>Comments</h3>

    <table class="table">
      <% @post.comments.each do |comment| %>
        
        <tr>
           <td style="color: #428bca;">
            <%= comment.user.name.capitalize %>
          </td>
          <td>
            <%= comment.title %>
          </td>

          <td class="text-right">
            <%= link_to 'Destroy', [@post,comment], method: :delete, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </table>

    <div class="row">
      <p class="col-md-6 text-left">
        <%= link_to 'Edit Post', edit_post_path(@post), class: 'btn btn-info' %>
        <%= link_to 'Back', posts_path, class: 'btn btn-default' %>
      </p>

      <p class="col-md-6 text-right">
        <%= link_to 'New Comment', new_post_comment_path(@post), class: 'btn btn-primary' %>
      </p>
    </div>
  </div>
</div>