config/routes.rb
Rails.application.routes.draw do
   devise_for :users

  devise_scope :user do
    authenticated :user do 
      root "posts#index", as: :authenticated_root
    end

    unauthenticated :user do 
      root "devise/sessions#new"
    end
  end

  resources :posts do
    resources :comments
  end

  get "friends" => "friends#user_list"
  get ":id/send_friend_request" => "friends#send_friend_request",as: :send_friend_request
  get ":id/manage_friend_request" => "friends#manage_friend_request",as: :manage_friend_request
  get ":id/unfriend" => "friends#unfriend",as: :unfriend
  get ":id/friend_of_friend" => "friends#friend_of_friend",as: :friend_of_friend
  get ":id/cancel_sended_frnd_req" => "friends#cancel_sended_frnd_req",as: :cancel_sended_frnd_req

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neo4j</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% if alert || notice %>
      <div class="text_center">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
      
    <% if  user_signed_in? %>
    <div class="heading" style="width:100%;background-color: bisque;">
      <span class="heading_left" style="width:80%;">  
        <span style="font-size:20px;">Neo4j Demo</span>
      </span>
      <span class="heading_left" style="width:20%; float:right;">
        <%=  current_user.name %> | <%= link_to "Sign out", destroy_user_session_path,method: :delete %>
      </span>
    </div>
    <div>
      <%= link_to "Posts", posts_path %> | 
      <%= link_to "Find Friends", friends_path%>
      <%= link_to "Back", :back,:style=>"float:right;" %>

    </div>  
  <% else %> 
    <div class="heading" style="width:100%;background-color: bisque;">
      <span class="heading_left"> 
        <span style="font-size:20px;">Neo4j Demo</span>
      </span>
    </div>
  <% end %>
    
    <%= yield %>
  </div>
</body>
</html>